language: rust

rust: nightly

addons:
  apt:
    packages:
    - ruby

os:
  - linux
  - osx

install:
  - git clone https://github.com/aquynh/capstone
  - (cd capstone && git checkout 3.0.4 && sudo make install)

script:
  - ./test
  - ./test-release
