[package]
name = "dora"
version = "0.0.1"
authors = ["Dominik Inführ <dominik.infuehr@gmail.com>"]

[dependencies]
phf = "*"
phf_macros = "*"
rustc-serialize = "*"
docopt = "*"
byteorder = "*"
libc = "*"
