[package]
name = "dora"
version = "0.0.1"
authors = ["Dominik Inführ <dominik.infuehr@gmail.com>"]

[dependencies]
rustc-serialize = "*"
docopt = "0.7"
byteorder = "*"
libc = "*"
time = "*"
dora-parser = { path = "lib/dora-parser" }
threadpool = "*"
crossbeam-deque = "0.6"
rand = "*"

[dependencies.capstone]
git = "https://github.com/ebfe/rust-capstone.git"

[profile.release]
panic = "abort"
